---
title: '2022-07-10'
author: "Maxwell Marion-Spencer"
date: '2022-07-10'
---

## ST 558 - Project 2 Blog Post

For ST 558 Project 2, my group partner - Xin Wang, and I automated Markdown output and built predictive models in order to analyze an online news popularity data set.

The predictive models we built were used to predict the number of shares. Each data channel had it's own output by topic, as the creation of Markdown files was automated. For each output, a best model was chosen based on which of the models had the lowest RMSE. 

The project went fairly smoothly, so I can't say that there is too much that I would do differently. I was a bit surprised at the computation time required for the random forest process. This was also the most difficult portion, just ensuring that I was going about building it correctly. I would say second-guessing myself about the computation time was the hardest part and I would look to just be more patient next time around!

My biggest takeaway from this project was just how powerful automating  outputs seems. I can imagine that there are many uses for something like this, the sports team example from the lecture was a great way of illustrating that. Being able to deliver a very solid baseline level of information in a report fairly easily, and then building from that foundation seems very valuable. 



Github Pages Repo: [https://maxwell-marion.github.io/project2-558/](https://maxwell-marion.github.io/project2-558/)

Regular Github Repo: [https://github.com/maxwell-marion/project2-558](https://github.com/maxwell-marion/project2-558)